/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32f4xx.h"
#include "led.h"
#include "SysTick.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif





int main(void) {
	for(int i=12; i<=15; i++)
	LedInit(i);

	SysTick_Config(SystemCoreClock / 1000);

	while(1) {
		LedOn(LED_GREEN);
		ST_DelayMs(100);
		LedOn(LED_ORANGE);
		ST_DelayMs(100);
		LedOn(LED_RED);
		ST_DelayMs(100);
		LedOn(LED_BLUE);
		ST_DelayMs(100);
		LedOff(LED_GREEN);
		ST_DelayMs(100);
		LedOff(LED_ORANGE);
		ST_DelayMs(100);
		LedOff(LED_RED);
		ST_DelayMs(100);
		LedOff(LED_BLUE);
		ST_DelayMs(100);

	}
	return 0;
}





