/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "led.h"
#include "timer.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {
	TimerInit();

	for(uint8_t i=12; i<=15; i++)
		led_init(i);

	while(1) {

		for(uint8_t i=12; i<=15; i++)
		led_on(i);

		TimerDelayMs(3000);

		for(uint8_t j=12; j<=15; j++)
			led_off(j);


		TimerDelayMs(7000);
	}
	return 0;
}

