/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "Timer.h"
#include "extin.h"
#include "uart.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

extern uint32_t count;

int main(void)
{
	char str[16];
	int duty;
	int cc=1;
	UartInit(9600);
	extint_init();
	TimerPwmInit();
	while(1)
	{
		if(count == 1)
		{
		    cc = 10;
		}
		else if(count == 2)
		{
		    cc = 1;
		    count = 0;
		}

		for(duty=0; duty<100;duty+=cc)
		{
			TIM8->CCR1 = duty;
			sprintf(str,"%d\r\n",duty);
			UartPuts(str);
			DelayMs(40);
		}
		for(duty=99;duty>=0;duty-=cc)
		{
			TIM8->CCR1 = duty;
			sprintf(str,"%d\r\n",duty);
			UartPuts(str);
			DelayMs(40);
		}
	}

}

