/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include"lcd.h"
#include"timer.h"

#include "rtc.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

static char str[50];
static char str1[50];
int main(void)
{
	RtcDate_t dt = { .date = 01, .month = 10, .year = 25, .weekday = 3 };
	RtcTime_t tm = { .hr = 13, .min = 01, .sec = 00 };

	LcdInit();
	RtcInit(&dt, &tm);
	while(1) {
		RtcGetTime(&tm);
		RtcGetDate(&dt);
		sprintf(str, "%02d-%02d-%02d (%d)", dt.date, dt.month, dt.year, dt.weekday);
		LcdPuts(LCD_LINE1, str);
		sprintf(str1, "%02d:%02d:%02d", tm.hr, tm.min, tm.sec);
		LcdPuts(LCD_LINE2, str1);

		TimerInit(1000);
	}
}


